kind: pipeline
type: docker
name: ci

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk
    commands:
      - dotnet build
      - dotnet publish -c Release -o out
  - name: test
    image: mcr.microsoft.com/dotnet/sdk
    volumes:
      - name: dockersock
        path: /var/run
    commands:
      - dotnet test
  - name: deliver
    image: docker
    commands: 
      - docker compose up -d

node:
  runner: drone-runner-1
  
volumes:
  - name: dockersock
    temp: {}