kind: pipeline
type: docker
name: ci

steps:
 - name: build
   image: mcr.microsoft.com/dotnet/sdk
   commands:
    - dotnet build
    - dotnet publish -c Release -o out
 - name: test
   image: mcr.microsoft.com/dotnet/sdk
   commands:
   - dotnet test

node:
  runner: drone-runner-1
        
---

kind: pipeline
type: exec
name: cd

platform:
  os: linux
  arch: amd64

steps:
  - name: compose
    commands: 
      - docker-compose up -d
        
node:
  runner: drone-runner-1