kind: pipeline
type: docker
name: default

steps:
 - name: build
   image: mcr.microsoft.com/dotnet/sdk
   commands:
    - dotnet build
    - dotnet publish -c Release -o out
 - name: test
   image: mcr.microsoft.com/dotnet/sdk
   commands:
   - dotnet test

node:
  runner: drone-runner-1
  
trigger:
    event:
      - push