version: "3.9"

services:
  counter-service:
    build:
      context: .
      dockerfile: DivisorCounter/Dockerfile
    image: kjel0393/counter-service
  cache-service:
    build:
      context: .
      dockerfile: CacheService/Dockerfile
    depends_on:
      - cache-db
    ports:
      - "5007:80"
    image: kjel0393/cache-service
  cache-db:
    image: "mysql"
    environment:
      MYSQL_DATABASE: "cache-database"
      MYSQL_USER: "div-cache"
      MYSQL_PASSWORD: "C@ch3d1v"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"